#!/bin/sh

set -e

gid=$(stat -c%g /tmp/.Xauthority)
uid=$(stat -c%u /tmp/.Xauthority)

if ! id dummy > /dev/null 2>&1; then
	groupadd -f -g "$gid" dummy
	useradd -g "$gid" -m -N -o -u "$uid" dummy
fi

if [ ! -d /home/dummy/.fx ]; then
	install -o "$uid" -g "$gid" -m 755 -d /home/dummy/.fx
	install -o "$uid" -g "$gid" -m 644 /tmp/.prefs.js /home/dummy/.fx/prefs.js
fi

if [ ! -f /home/dummy/.fx/cert9.db ]; then
	pid=$(su -c "nohup firefox -no-remote -profile /home/dummy/.fx > /dev/null 2>&1 & printf '%s' \"\$!\"" dummy)
	sleep 2
	while [ ! -f "/home/dummy/.fx/cert9.db" ]; do
		sleep 2
	done
	kill -9 $pid
fi

if [ ! -f /home/dummy/warsaw.cer ]; then
	install -o "$uid" -g "$gid" -m 644 /tmp/.warsaw.cer /home/dummy/warsaw.cer
	su -c 'certutil -D -n "Warsaw Personal CA" -d sql:/home/dummy/.fx > /dev/null 2>&1; certutil -A -n "Warsaw Personal CA" -t "TCu,Cu,Tuw" -i /home/dummy/warsaw.cer -d sql:/home/dummy/.fx' dummy
fi

/usr/local/bin/warsaw/core

sleep 1

exec su -c '/usr/local/bin/warsaw/core && exec firefox -no-remote -profile /home/dummy/.fx https://www2.bancobrasil.com.br/aapf/login.jsp' dummy
